#--------------------------------------
# Image: base
#--------------------------------------
ARG BASE_IMAGE=containerbase/base

FROM ${BASE_IMAGE} as base

RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG
ARG GITHUB_TOKEN

RUN uname -p | tee | grep aarch64

#--------------------------------------
# Image: flutter
#--------------------------------------
FROM base as test-flutter

# renovate: datasource=flutter-version
RUN install-tool flutter 3.16.9

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-flutter /.dummy /.dummy
