#--------------------------------------
# Image: base
#--------------------------------------
ARG BASE_IMAGE=containerbase/base

FROM ${BASE_IMAGE} as base

RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG
ARG GITHUB_TOKEN

RUN uname -p | tee | grep aarch64

#--------------------------------------
# Image: swift
#--------------------------------------
FROM base as test-swift

# renovate: datasource=docker versioning=docker
RUN install-tool swift 5.9.2

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-swift /.dummy /.dummy
