#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:focal as base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG

ENV BASH_ENV=/opt/containerbase/env
SHELL ["/bin/bash" , "-c"]

COPY src/ /

RUN install-containerbase

# renovate: datasource=github-tags packageName=git/git
# RUN install-tool git v2.40.0

#--------------------------------------
# Image: swift
#--------------------------------------
FROM base as test-swift

# renovate: datasource=docker versioning=docker
RUN install-tool swift 5.8.0

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-swift /.dummy /.dummy
