#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:bionic as base

ARG APT_HTTP_PROXY

LABEL maintainer="Rhys Arkins <rhys@arkins.net>" \
  org.opencontainers.image.source="https://github.com/containerbase/buildpack"

#  autoloading buildpack env
ENV BASH_ENV=/usr/local/etc/env ENV=/usr/local/etc/env PATH=/home/$USER_NAME/bin:$PATH
SHELL ["/bin/bash" , "-c"]

COPY src/ /

RUN install-buildpack


# renovate: datasource=github-tags packageName=git/git
RUN install-tool git v2.38.1


#--------------------------------------
# Image: test
#--------------------------------------
FROM base as test

ARG APT_HTTP_PROXY

# renovate: datasource=docker packageName=mcr.microsoft.com/dotnet/sdk versioning=docker
RUN install-tool dotnet 6.0.403

# renovate: datasource=github-releases packageName=containerbase/erlang-prebuild versioning=docker
RUN install-tool erlang 25.1.2.0
# renovate: datasource=docker versioning=docker
RUN install-tool elixir 1.14.2

# renovate datasource=flutter-version
RUN install-tool flutter 3.0.2

# renovate: datasource=github-releases packageName=fluxcd/flux2
RUN install-tool flux v0.36.0

# renovate: datasource=docker versioning=docker
RUN install-tool golang 1.19.3

# renovate: datasource=github-releases packageName=helm/helm
RUN install-tool helm v3.10.2

# renovate: datasource=adoptium-java packageName=java-jre
RUN install-tool java 17.0.5+8
# renovate: datasource=gradle-version packageName=gradle versioning=gradle
RUN install-tool gradle 7.5.1

# renovate: datasource=github-tags packageName=NixOS/nix
RUN install-tool nix 2.11.1

# renovate: datasource=node
RUN install-tool node v16.18.1
# renovate: datasource=npm
RUN install-tool pnpm 7.15.0
# renovate: datasource=npm
RUN install-tool yarn 1.22.19
# renovate: datasource=npm
RUN install-npm lerna 6.0.3

# renovate: datasource=github-releases packageName=containerbase/php-prebuild
RUN install-tool php 8.1.12
# renovate: datasource=github-releases packageName=composer/composer
RUN install-tool composer 2.4.4

# renovate: datasource=github-releases packageName=PowerShell/PowerShell
RUN install-tool powershell v7.2.7

# renovate: datasource=github-releases packageName=containerbase/python-prebuild
RUN install-tool python 3.11.0
# renovate: datasource=pypi
RUN install-pip pipenv 2022.11.11
# renovate: datasource=pypi
RUN install-pip hashin 0.17.0
# renovate: datasource=pypi
RUN install-tool poetry 1.2.2

# renovate: datasource=github-releases packageName=containerbase/ruby-prebuild versioning=ruby
RUN install-tool ruby 3.1.2
# renovate: datasource=rubygems versioning=ruby
RUN install-tool bundler 2.3.26
# renovate: datasource=rubygems versioning=ruby
RUN install-tool cocoapods 1.11.3

# renovate: datasource=docker versioning=docker
RUN install-tool rust 1.65.0

# renovate: datasource=docker versioning=docker
RUN install-tool swift 5.7.1

# renovate: datasource=docker packageName=hashicorp/terraform versioning=docker
RUN install-tool terraform 1.3.4

# renovate: datasource=github-releases packageName=git-lfs/git-lfs
RUN install-tool git-lfs v3.1.4
RUN git lfs version

# renovate: datasource=github-releases packageName=jsonnet-bundler/jsonnet-bundler
RUN install-tool jb v0.5.1
