#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:jammy as base

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG

COPY src/ /

RUN install-containerbase

# renovate: datasource=github-tags packageName=git/git
RUN install-tool git v2.42.0

#--------------------------------------
# Image: build
#--------------------------------------
FROM base as build

RUN uname -p | tee | grep x86_64

RUN touch /.dummy

RUN prepare-tool all

#--------------------------------------
# Image: test
#--------------------------------------
FROM build as test

# renovate: datasource=npm
RUN install-tool bun 1.0.2

# renovate datasource=docker
RUN install-tool dart 2.18.0

# renovate: datasource=github-releases packageName=moby/moby
RUN install-tool docker v24.0.6

# renovate: datasource=dotnet packageName=dotnet-sdk
RUN install-tool dotnet 7.0.401

# renovate datasource=flutter-version
RUN install-tool flutter 3.0.2

# renovate: datasource=github-releases packageName=fluxcd/flux2
RUN install-tool flux v2.1.1

# renovate: datasource=github-releases packageName=git-lfs/git-lfs
RUN install-tool git-lfs v3.4.0

# renovate: datasource=docker versioning=docker
RUN install-tool golang 1.21.1

# renovate: datasource=github-releases packageName=helm/helm
RUN install-tool helm v3.13.0

# renovate: datasource=github-releases packageName=helmfile/helmfile
RUN install-tool helmfile v0.156.0

# renovate: datasource=github-releases packageName=kubernetes-sigs/kustomize
RUN install-tool kustomize 5.1.1

# renovate: datasource=github-tags packageName=NixOS/nix
RUN install-tool nix 2.17.1

# renovate: datasource=github-releases packageName=PowerShell/PowerShell
RUN install-tool powershell v7.3.7

# renovate: datasource=docker versioning=docker
RUN install-tool rust 1.72.1

# renovate: datasource=docker versioning=docker
RUN install-tool swift 5.9.0

# renovate: datasource=docker packageName=hashicorp/terraform versioning=docker
RUN install-tool terraform 1.5.7

# renovate: datasource=github-releases packageName=jsonnet-bundler/jsonnet-bundler
RUN install-tool jb v0.5.1

# renovate: datasource=github-releases packageName=vmware-tanzu/carvel-vendir
RUN install-tool vendir v0.35.0

#--------------------------------------
# Image: test-erlang
#--------------------------------------
FROM build as test-erlang

# renovate: datasource=github-releases packageName=containerbase/erlang-prebuild versioning=docker
RUN install-tool erlang 26.0.2.0
# renovate: datasource=docker versioning=docker
RUN install-tool elixir 1.15.4

#--------------------------------------
# Image: test-java
#--------------------------------------
FROM build as test-java

# renovate: datasource=adoptium-java packageName=java-jre
RUN install-tool java 17.0.8+101
# renovate: datasource=gradle-version packageName=gradle versioning=gradle
RUN install-tool gradle 8.3

#--------------------------------------
# Image: test-node
#--------------------------------------
FROM build as test-node

# renovate: datasource=node
RUN install-tool node v18.18.0
# renovate: datasource=npm
RUN install-tool pnpm 8.7.6
# renovate: datasource=npm
RUN install-tool yarn 1.22.19
# renovate: datasource=npm
RUN install-tool lerna 7.3.0

#--------------------------------------
# Image: test-python
#--------------------------------------
FROM build as test-php

# renovate: datasource=github-releases packageName=containerbase/php-prebuild
RUN install-tool php 8.2.10
# renovate: datasource=github-releases packageName=composer/composer
RUN install-tool composer 2.6.3

#--------------------------------------
# Image: test-python
#--------------------------------------
FROM build as test-python

# renovate: datasource=github-releases packageName=containerbase/python-prebuild
RUN install-tool python 3.11.5
# renovate: datasource=pypi
RUN install-tool pipenv 2023.9.8
# renovate: datasource=pypi
RUN install-tool hashin 0.17.0
# renovate: datasource=pypi
RUN install-tool poetry 1.6.1
# renovate: datasource=pypi
RUN install-tool pdm 2.9.3

#--------------------------------------
# Image: test-ruby
#--------------------------------------
FROM build as test-ruby

# renovate: datasource=github-releases packageName=containerbase/ruby-prebuild versioning=ruby
RUN install-tool ruby 3.2.2
# renovate: datasource=rubygems versioning=ruby
RUN install-tool bundler 2.4.20
# renovate: datasource=rubygems versioning=ruby
RUN install-tool cocoapods 1.12.1

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test /.dummy /.dummy
COPY --from=test-erlang /.dummy /.dummy
COPY --from=test-java /.dummy /.dummy
COPY --from=test-node /.dummy /.dummy
COPY --from=test-php /.dummy /.dummy
COPY --from=test-python /.dummy /.dummy
COPY --from=test-ruby /.dummy /.dummy
