ARG BASE_IMAGE=latest


#--------------------------------------
# Images
#--------------------------------------
FROM ghcr.io/containerbase/ubuntu:20.04 AS focal
FROM ghcr.io/containerbase/ubuntu:22.04 AS jammy
FROM ghcr.io/containerbase/ubuntu:24.04 AS noble

FROM ghcr.io/containerbase/ubuntu:24.04 AS latest
#--------------------------------------
# Image: base
#--------------------------------------
FROM ${BASE_IMAGE} AS base

ARG TARGETARCH
COPY dist/docker/ /
COPY dist/cli/containerbase-cli-${TARGETARCH} /usr/local/containerbase/bin/containerbase-cli

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG
ARG CONTAINERBASE_CDN
ARG CONTAINERBASE_LOG_LEVEL

RUN install-containerbase

# renovate: datasource=github-tags packageName=git/git
RUN install-tool git v2.51.0

#--------------------------------------
# Image: build
#--------------------------------------
FROM base AS build

RUN uname -p | tee | grep x86_64

RUN touch /.dummy

RUN prepare-tool all

#--------------------------------------
# Image: test
#--------------------------------------
FROM build AS test

# renovate: datasource=github-releases packageName=bazelbuild/bazelisk
RUN install-tool bazelisk v1.27.0

# renovate: datasource=npm
RUN install-tool bun 1.2.21

# renovate: datasource=docker
RUN install-tool dart 3.9.2

# renovate: datasource=github-releases packageName=denoland/deno
RUN install-tool deno 2.4.5

# renovate: datasource=github-releases packageName=jetify-com/devbox
RUN install-tool devbox 0.16.0

# renovate: datasource=github-releases packageName=moby/moby
RUN install-tool docker v28.4.0

# renovate: datasource=dotnet packageName=dotnet-sdk
RUN install-tool dotnet 9.0.304

# renovate: datasource=github-releases packageName=containerbase/flutter-prebuild
RUN install-tool flutter 3.35.2

# renovate: datasource=github-releases packageName=fluxcd/flux2
RUN install-tool flux v2.6.4

# renovate: datasource=github-releases packageName=git-lfs/git-lfs
RUN install-tool git-lfs v3.7.0

# renovate: datasource=github-releases packageName=gleam-lang/gleam
RUN install-tool gleam 1.12.0

# renovate: datasource=github-releases packageName=containerbase/golang-prebuild
RUN install-tool golang 1.24.7

# renovate: datasource=github-releases packageName=helm/helm
RUN install-tool helm v3.18.6

# renovate: datasource=github-releases packageName=helmfile/helmfile
RUN install-tool helmfile v1.1.6

# renovate: datasource=github-releases packageName=kubernetes/kubernetes
RUN install-tool kubectl v1.34.0

# renovate: datasource=github-releases packageName=kubernetes-sigs/kustomize
RUN install-tool kustomize 5.7.1

# renovate: datasource=datasource=github-releases packageName=containerbase/nix-prebuild
RUN install-tool nix 2.24.10

# renovate: datasource=github-releases packageName=prefix-dev/pixi
RUN install-tool pixi v0.54.1

# renovate: datasource=github-releases packageName=PowerShell/PowerShell
RUN install-tool powershell v7.5.2

# renovate: datasource=docker versioning=docker
RUN install-tool rust 1.89.0

# renovate: datasource=github-releases packageName=containerbase/skopeo-prebuild
RUN install-tool skopeo 1.20.0

# renovate: datasource=github-releases packageName=getsops/sops
RUN install-tool sops v3.10.2

# renovate: datasource=docker versioning=docker
RUN install-tool swift 6.1.2

# renovate: datasource=docker packageName=hashicorp/terraform versioning=docker
RUN install-tool terraform 1.13.1

# renovate: datasource=github-releases packageName=jsonnet-bundler/jsonnet-bundler
RUN install-tool jb v0.6.0

# renovate: datasource=github-releases packageName=vmware-tanzu/carvel-vendir
RUN install-tool vendir v0.44.0

# renovate: datasource=github-releases packageName=containerbase/wally-prebuild
RUN install-tool wally 0.3.2

# renovate: datasource=github-releases packageName=protocolbuffers/protobuf
RUN install-tool protoc 29.2

#--------------------------------------
# Image: test-erlang
#--------------------------------------
FROM build AS test-erlang

# renovate: datasource=github-releases packageName=containerbase/erlang-prebuild versioning=docker
RUN install-tool erlang 27.3.4.2
# renovate: datasource=github-releases packageName=elixir-lang/elixir
RUN install-tool elixir 1.18.4

#--------------------------------------
# Image: test-java
#--------------------------------------
FROM build AS test-java

# renovate: datasource=java-version packageName=java-jre?os=linux&architecture=x64
RUN install-tool java 21.0.8+9.0.LTS
# renovate: datasource=gradle-version packageName=gradle versioning=gradle
RUN install-tool gradle 9.0.0

#--------------------------------------
# Image: test-node
#--------------------------------------
FROM build AS test-node

# renovate: datasource=github-releases packageName=containerbase/node-prebuild versioning=node
RUN install-tool node 22.19.0
# renovate: datasource=npm
RUN install-tool pnpm 10.15.1
# renovate: datasource=npm packageName=@yarnpkg/cli-dist
RUN install-tool yarn 4.9.4

#--------------------------------------
# Image: test-php
#--------------------------------------
FROM build AS test-php

# renovate: datasource=github-releases packageName=containerbase/php-prebuild
RUN install-tool php 8.4.12
# renovate: datasource=github-releases packageName=containerbase/composer-prebuild
RUN install-tool composer 2.8.11

#--------------------------------------
# Image: test-python
#--------------------------------------
FROM build AS test-python

# renovate: datasource=github-releases packageName=containerbase/python-prebuild
RUN install-tool python 3.13.7

# renovate: datasource=pypi
RUN install-tool checkov 3.2.468
# renovate: datasource=pypi
RUN install-tool conan 2.20.1
# renovate: datasource=pypi
RUN install-tool copier 9.10.1
# renovate: datasource=pypi
RUN install-tool hashin 1.0.5
# renovate: datasource=pypi
RUN install-tool pipenv 2025.0.4
# renovate: datasource=pypi
RUN install-tool pdm 2.25.9
# renovate: datasource=pypi
RUN install-tool poetry 2.1.4
# renovate: datasource=pypi
RUN install-tool uv 0.8.15

#--------------------------------------
# Image: test-ruby
#--------------------------------------
FROM build AS test-ruby

# renovate: datasource=github-releases packageName=containerbase/ruby-prebuild versioning=ruby
RUN install-tool ruby 3.4.5
# renovate: datasource=rubygems versioning=ruby
RUN install-tool bundler 2.7.1
# renovate: datasource=rubygems versioning=ruby
RUN install-tool cocoapods 1.16.2

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test /.dummy /.dummy
COPY --from=test-erlang /.dummy /.dummy
COPY --from=test-java /.dummy /.dummy
COPY --from=test-node /.dummy /.dummy
COPY --from=test-php /.dummy /.dummy
COPY --from=test-python /.dummy /.dummy
COPY --from=test-ruby /.dummy /.dummy
