#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:noble as base

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG
ARG CONTAINERBASE_CDN

ARG TARGETARCH

COPY dist/docker/ /
COPY dist/cli/containerbase-cli-${TARGETARCH} /usr/local/containerbase/bin/containerbase-cli

RUN install-containerbase

# renovate: datasource=github-tags packageName=git/git
RUN install-tool git v2.45.2

#--------------------------------------
# Image: build
#--------------------------------------
FROM base as build

RUN uname -p | tee | grep x86_64

RUN touch /.dummy

RUN prepare-tool all

#--------------------------------------
# Image: test
#--------------------------------------
FROM build as test

# renovate: datasource=github-releases packageName=bazelbuild/bazelisk
RUN install-tool bazelisk v1.20.0

# renovate: datasource=npm
RUN install-tool bun 1.1.12

# renovate: datasource=docker
RUN install-tool dart 2.19.6

# renovate: datasource=github-releases packageName=moby/moby
RUN install-tool docker v26.1.4

# renovate: datasource=dotnet packageName=dotnet-sdk
RUN install-tool dotnet 8.0.301

# renovate: datasource=flutter-version
RUN install-tool flutter 3.22.2

# renovate: datasource=github-releases packageName=fluxcd/flux2
RUN install-tool flux v2.3.0

# renovate: datasource=github-releases packageName=git-lfs/git-lfs
RUN install-tool git-lfs v3.5.1

# renovate: datasource=github-releases packageName=gleam-lang/gleam
RUN install-tool gleam 1.2.1

# renovate: datasource=docker versioning=docker
RUN install-tool golang 1.22.4

# renovate: datasource=github-releases packageName=helm/helm
RUN install-tool helm v3.15.1

# renovate: datasource=github-releases packageName=helmfile/helmfile
RUN install-tool helmfile v0.165.0

# renovate: datasource=github-releases packageName=kubernetes-sigs/kustomize
RUN install-tool kustomize 5.4.2

# renovate: datasource=github-tags packageName=NixOS/nix
RUN install-tool nix 2.22.1

# renovate: datasource=github-releases packageName=PowerShell/PowerShell
RUN install-tool powershell v7.4.2

# renovate: datasource=docker versioning=docker
RUN install-tool rust 1.78.0

# renovate: datasource=docker versioning=docker
RUN install-tool swift 5.10.0

# renovate: datasource=docker packageName=hashicorp/terraform versioning=docker
RUN install-tool terraform 1.8.5

# renovate: datasource=github-releases packageName=jsonnet-bundler/jsonnet-bundler
RUN install-tool jb v0.5.1

# renovate: datasource=github-releases packageName=vmware-tanzu/carvel-vendir
RUN install-tool vendir v0.40.1

#--------------------------------------
# Image: test-erlang
#--------------------------------------
FROM build as test-erlang

# renovate: datasource=github-releases packageName=containerbase/erlang-prebuild versioning=docker
RUN install-tool erlang 26.2.5.0
# renovate: datasource=docker versioning=docker
RUN install-tool elixir 1.16.3

#--------------------------------------
# Image: test-java
#--------------------------------------
FROM build as test-java

# renovate: datasource=adoptium-java packageName=java-jre
RUN install-tool java 21.0.3+9.0.LTS
# renovate: datasource=gradle-version packageName=gradle versioning=gradle
RUN install-tool gradle 8.8

#--------------------------------------
# Image: test-node
#--------------------------------------
FROM build as test-node

# renovate: datasource=node
RUN install-tool node v20.14.0
# renovate: datasource=npm
RUN install-tool pnpm 9.1.4
# renovate: datasource=npm packageName=@yarnpkg/cli-dist
RUN install-tool yarn 4.2.2

#--------------------------------------
# Image: test-php
#--------------------------------------
FROM build as test-php

# renovate: datasource=github-releases packageName=containerbase/php-prebuild
RUN install-tool php 8.3.8
# renovate: datasource=github-releases packageName=composer/composer
RUN install-tool composer 2.7.6

#--------------------------------------
# Image: test-python
#--------------------------------------
FROM build as test-python

# renovate: datasource=github-releases packageName=containerbase/python-prebuild
RUN install-tool python 3.12.3
# renovate: datasource=pypi
RUN install-tool conan 2.4.0
# renovate: datasource=pypi
RUN install-tool hashin 1.0.1
# renovate: datasource=pypi
RUN install-tool pipenv 2023.12.1
# renovate: datasource=pypi
RUN install-tool pdm 2.15.4
# renovate: datasource=pypi
RUN install-tool poetry 1.8.3

#--------------------------------------
# Image: test-ruby
#--------------------------------------
FROM build as test-ruby

# renovate: datasource=github-releases packageName=containerbase/ruby-prebuild versioning=ruby
RUN install-tool ruby 3.3.2
# renovate: datasource=rubygems versioning=ruby
RUN install-tool bundler 2.5.11
# renovate: datasource=rubygems versioning=ruby
RUN install-tool cocoapods 1.15.2

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test /.dummy /.dummy
COPY --from=test-erlang /.dummy /.dummy
COPY --from=test-java /.dummy /.dummy
COPY --from=test-node /.dummy /.dummy
COPY --from=test-php /.dummy /.dummy
COPY --from=test-python /.dummy /.dummy
COPY --from=test-ruby /.dummy /.dummy
