#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:bionic@sha256:7bd7a9ca99f868bf69c4b6212f64f2af8e243f97ba13abb3e641e03a7ceb59e8 as base

ARG APT_HTTP_PROXY

LABEL maintainer="Rhys Arkins <rhys@arkins.net>" \
  org.opencontainers.image.source="https://github.com/containerbase/buildpack"

#  autoloading buildpack env
ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

COPY src/ /

RUN install-buildpack


# renovate: datasource=github-tags lookupName=git/git
RUN install-tool git v2.33.0


#--------------------------------------
# Image: test
#--------------------------------------
FROM base as test

ARG APT_HTTP_PROXY

# renovate: datasource=docker lookupName=mcr.microsoft.com/dotnet/sdk versioning=docker
RUN install-tool dotnet 3.1.412

#disable renovate: datasource=github-releases lookupName=erlang/otp versioning=loose
RUN install-tool erlang 22.3.2
# renovate: datasource=docker versioning=docker
RUN install-tool elixir 1.12.2

# renovate: datasource=docker versioning=docker
RUN install-tool golang 1.17.0

# renovate: datasource=github-releases lookupName=helm/helm
RUN install-tool helm v3.6.3

# renovate: datasource=adoptium-java
RUN install-tool java 11.0.12+7
# renovate: datasource=gradle-version lookupName=gradle versioning=gradle
RUN install-tool gradle 7.2

# renovate: datasource=github-releases lookupName=NixOS/nix
RUN install-tool nix 2.3.10

# renovate: datasource=docker versioning=docker
RUN install-tool node 14.17.5
# renovate: datasource=npm
RUN install-tool pnpm 6.11.5
# renovate: datasource=npm
RUN install-tool yarn 1.22.11
# renovate: datasource=npm
RUN install-npm lerna 4.0.0

# renovate: datasource=github-releases lookupName=containerbase/php-prebuild
RUN install-tool php 8.0.9
# renovate: datasource=github-releases lookupName=composer/composer
RUN install-tool composer 2.1.6

# renovate: datasource=github-releases lookupName=PowerShell/PowerShell
RUN install-tool powershell v7.1.4

# renovate: datasource=github-releases lookupName=containerbase/python-prebuild
RUN install-tool python 3.9.6
# renovate: datasource=pypi
RUN install-pip pipenv 2021.5.29
# renovate: datasource=pypi
RUN install-pip hashin 0.15.0
# renovate: datasource=pypi
RUN install-tool poetry 1.1.8

# renovate: datasource=github-releases lookupName=containerbase/ruby-prebuild versioning=ruby
RUN install-tool ruby 3.0.2
# renovate: datasource=rubygems versioning=ruby
RUN install-gem bundler 2.2.26
# renovate: datasource=rubygems versioning=ruby
RUN install-gem cocoapods 1.10.2

# renovate: datasource=docker versioning=docker
RUN install-tool rust 1.54.0

# renovate: datasource=docker versioning=docker
RUN install-tool swift 5.4.2

# renovate: datasource=docker lookupName=hashicorp/terraform versioning=docker
RUN install-tool terraform 1.0.5

# renovate: datasource=github-releases lookupName=git-lfs/git-lfs
RUN install-tool git-lfs v2.13.3
