#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:focal as base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

COPY src/ /

RUN install-containerbase

#--------------------------------------
# Image: node
#--------------------------------------
FROM base as test-node

# renovate: datasource=node
RUN install-tool node v18.16.0

#--------------------------------------
# Image: lerna
#--------------------------------------
FROM test-node as test-lerna

# renovate: datasource=npm
RUN install-tool lerna 6.6.1

#--------------------------------------
# Image: pnpm
#--------------------------------------
FROM test-node as test-pnpm

# renovate: datasource=npm
RUN install-tool pnpm 8.4.0

#--------------------------------------
# Image: yarn
#--------------------------------------
FROM test-node as test-yarn

# renovate: datasource=npm
RUN install-tool yarn 1.22.19

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-node /.dummy /.dummy
# fails locally
# COPY --from=test-lerna /.dummy /.dummy
COPY --from=test-pnpm /.dummy /.dummy
COPY --from=test-yarn /.dummy /.dummy

