#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:focal AS base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_CDN
ARG CONTAINERBASE_DEBUG

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

ARG TARGETARCH

COPY dist/docker/ /
COPY dist/cli/containerbase-cli-${TARGETARCH} /usr/local/containerbase/bin/containerbase-cli

RUN install-containerbase

#--------------------------------------
# Image: node
#--------------------------------------
FROM base AS test-node

# renovate: datasource=node
RUN install-tool node v20.15.0


#--------------------------------------
# Image: pnpm
#--------------------------------------
FROM test-node AS test-pnpm

# renovate: datasource=npm
RUN install-tool pnpm 9.4.0

#--------------------------------------
# Image: yarn
#--------------------------------------
FROM test-node AS test-yarn

# renovate: datasource=npm
RUN install-tool yarn 1.22.22

#--------------------------------------
# Image: renovate
#--------------------------------------
FROM test-node AS test-renovate

# renovate: datasource=npm
RUN install-tool renovate 37.421.3

# ARG RE2_DOWNLOAD_MIRROR=https://github.com/containerbase/node-re2-prebuild/releases/download RE2_DOWNLOAD_SKIP_PATH=1
# # renovate: datasource=npm
# RUN npm install -g re2@1.20.9

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-node /.dummy /.dummy
COPY --from=test-pnpm /.dummy /.dummy
COPY --from=test-yarn /.dummy /.dummy
COPY --from=test-renovate /.dummy /.dummy
