packages: []
allowUnusedPatches: true

strictPeerDependencies: true

allowBuilds:
  esbuild: false
  unrs-resolver: false

overrides:
  verbose: '-'

patchedDependencies:
  clipanion@3.2.1: patches/clipanion@3.2.1.patch
  global-agent: patches/global-agent.patch

# in line with https://github.com/containerbase/.github/blob/main/default.json,
# all non-Renovate or non-Containerbase packages should only be installed after
# 3 days
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@renovatebot/detect-tools'
  - '@renovatebot/osv-offline'
  - '@renovatebot/pep440'
  - '@renovatebot/pgp'
  - '@renovatebot/ruby-semver'
  - '@containerbase/eslint-plugin'
  - '@containerbase/istanbul-reports-html'
  - '@containerbase/semantic-release-pnpm'
