packages:
  - packages/*
allowUnusedPatches: true

updateNotifier: false

saveExact: true

strictPeerDependencies: true

allowBuilds:
  esbuild: false
  unrs-resolver: false

overrides:
  http-cache-semantics@<=4.2.0: 4.3.0
  katex@>=0.11.0 <0.18.2: 0.19.0
  shell-quote@>=1.8.4 <1.11.0: 1.12.0
  smol-toml@<=1.8.0: 1.9.0
  source-map-js@>=1.0.0 <1.2.2: 1.2.2
  verbose: '-'

patchedDependencies:
  clipanion@3.2.1: patches/clipanion@3.2.1.patch
  global-agent: patches/global-agent.patch

# in line with https://github.com/containerbase/.github/blob/main/default.json,
# all non-Renovate or non-Containerbase packages should only be installed after
# 3 days
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@renovatebot/detect-tools'
  - '@renovatebot/osv-offline'
  - '@renovatebot/pep440'
  - '@renovatebot/pgp'
  - '@renovatebot/ruby-semver'
  - '@containerbase/istanbul-reports-html'
  - '@containerbase/oxlint-plugin'
  - '@containerbase/semantic-release-pnpm'
