#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:focal as base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

COPY src/ /

RUN install-containerbase

#--------------------------------------
# Image: rust
#--------------------------------------
FROM base as test-rust

# renovate: datasource=docker versioning=docker
RUN install-tool rust 1.72.1

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-rust /.dummy /.dummy
