#--------------------------------------
# Image: base
#--------------------------------------
ARG BASE_IMAGE=containerbase/base

FROM ${BASE_IMAGE} as base

RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG
ARG GITHUB_TOKEN

RUN uname -p | tee | grep aarch64

#--------------------------------------
# Image: rust
#--------------------------------------
FROM base as test-rust

# renovate: datasource=docker versioning=docker
RUN install-tool rust 1.75.0

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-rust /.dummy /.dummy
