#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:focal as base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

ARG TARGETARCH

COPY dist/docker/ /
COPY dist/cli/containerbase-cli-${TARGETARCH} /usr/local/containerbase/bin/containerbase-cli

RUN install-containerbase

#--------------------------------------
# Image: erlang
#--------------------------------------
FROM base as test-erlang

# renovate: datasource=github-releases packageName=containerbase/erlang-prebuild versioning=docker
RUN install-tool erlang 26.2.5.0

#--------------------------------------
# Image: elixir
#--------------------------------------
FROM test-erlang as test-elixir

# renovate: datasource=docker versioning=docker
RUN install-tool elixir 1.16.2

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-erlang /.dummy /.dummy
COPY --from=test-elixir /.dummy /.dummy
