#--------------------------------------
# Image: base
#--------------------------------------
ARG BASE_IMAGE=containerbase/base

FROM ${BASE_IMAGE} as base

RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG
ARG GITHUB_TOKEN

RUN uname -p | tee | grep aarch64

#--------------------------------------
# Image: test
#--------------------------------------
FROM base as test-powershell

# renovate: datasource=github-releases packageName=PowerShell/PowerShell
RUN install-tool powershell v7.4.1

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-powershell /.dummy /.dummy
