#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:focal AS base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_CDN
ARG CONTAINERBASE_DEBUG

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

ARG TARGETARCH

COPY dist/docker/ /
COPY dist/cli/containerbase-cli-${TARGETARCH} /usr/local/containerbase/bin/containerbase-cli

RUN install-containerbase

#--------------------------------------
# Image: test
#--------------------------------------
FROM base AS test-powershell

# renovate: datasource=github-releases packageName=PowerShell/PowerShell
RUN install-tool powershell v7.4.3

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-powershell /.dummy /.dummy
