#--------------------------------------
# Image: base
#--------------------------------------
ARG BASE_IMAGE=containerbase/base

FROM ${BASE_IMAGE} as base

RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG
ARG GITHUB_TOKEN

RUN uname -p | tee | grep aarch64

#--------------------------------------
# Image: jb
#--------------------------------------
FROM base as test-jb

# renovate: datasource=github-releases packageName=jsonnet-bundler/jsonnet-bundler
RUN install-tool jb v0.5.1

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-jb /.dummy /.dummy
