#--------------------------------------
# Image: base
#--------------------------------------
ARG BASE_IMAGE=containerbase/base

FROM ${BASE_IMAGE} as base

RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG
ARG GITHUB_TOKEN

RUN uname -p | tee | grep aarch64

#--------------------------------------
# Image: ruby
#--------------------------------------
FROM base as test-ruby

# renovate: datasource=github-releases packageName=containerbase/ruby-prebuild versioning=ruby
RUN install-tool ruby 3.2.3

#--------------------------------------
# Image: bundler
#--------------------------------------
FROM test-ruby as test-bundler

# renovate: datasource=rubygems versioning=ruby
RUN install-tool bundler 2.5.5

#--------------------------------------
# Image: cocoapods
#--------------------------------------
FROM test-ruby as test-cocoapods

# renovate: datasource=rubygems versioning=ruby
RUN install-tool cocoapods 1.15.0

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-ruby /.dummy /.dummy
COPY --from=test-bundler /.dummy /.dummy
COPY --from=test-cocoapods /.dummy /.dummy
