ARG BASE_IMAGE=containerbase

#--------------------------------------
# Image: containerbase
#--------------------------------------
FROM ghcr.io/containerbase/ubuntu:20.04 AS containerbase

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

ARG TARGETARCH
COPY dist/docker/ /
COPY dist/cli/containerbase-cli-${TARGETARCH} /usr/local/containerbase/bin/containerbase-cli

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_CDN
ARG CONTAINERBASE_DEBUG
ARG CONTAINERBASE_LOG_LEVEL

RUN install-containerbase

#--------------------------------------
# Image: base
#--------------------------------------
FROM ${BASE_IMAGE} AS base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_CDN
ARG CONTAINERBASE_DEBUG
ARG CONTAINERBASE_LOG_LEVEL

#--------------------------------------
# Image: ruby
#--------------------------------------
FROM base AS test-ruby

# renovate: datasource=github-releases packageName=containerbase/ruby-prebuild versioning=ruby
RUN install-tool ruby 3.3.5

#--------------------------------------
# Image: bundler
#--------------------------------------
FROM test-ruby AS test-bundler

# renovate: datasource=rubygems versioning=ruby
RUN install-tool bundler 2.5.21

#--------------------------------------
# Image: cocoapods
#--------------------------------------
FROM test-ruby AS test-cocoapods

# cocoapods need git, but don't install yet
# renovate: datasource=github-tags packageName=git/git
RUN install-tool git v2.46.2

# renovate: datasource=rubygems versioning=ruby
RUN install-tool cocoapods 1.15.2

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-ruby /.dummy /.dummy
COPY --from=test-bundler /.dummy /.dummy
COPY --from=test-cocoapods /.dummy /.dummy
