#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:focal as base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

ARG TARGETARCH

COPY dist/docker/ /
COPY dist/cli/containerbase-cli-${TARGETARCH} /usr/local/containerbase/bin/containerbase-cli

RUN install-containerbase

#--------------------------------------
# Image: ruby
#--------------------------------------
FROM base as test-ruby

# renovate: datasource=github-releases packageName=containerbase/ruby-prebuild versioning=ruby
RUN install-tool ruby 3.3.2

#--------------------------------------
# Image: bundler
#--------------------------------------
FROM test-ruby as test-bundler

# renovate: datasource=rubygems versioning=ruby
RUN install-tool bundler 2.5.11

#--------------------------------------
# Image: cocoapods
#--------------------------------------
FROM test-ruby as test-cocoapods

# cocoapods need git, but don't install yet
# renovate: datasource=github-tags packageName=git/git
RUN install-tool git v2.45.1

# renovate: datasource=rubygems versioning=ruby
RUN install-tool cocoapods 1.15.2

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-ruby /.dummy /.dummy
COPY --from=test-bundler /.dummy /.dummy
COPY --from=test-cocoapods /.dummy /.dummy
