ARG BASE_IMAGE=containerbase

#--------------------------------------
# Image: containerbase
#--------------------------------------
FROM ghcr.io/containerbase/ubuntu:20.04 AS containerbase

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

ARG TARGETARCH
COPY dist/docker/ /
COPY dist/cli/containerbase-cli-${TARGETARCH} /usr/local/containerbase/bin/containerbase-cli

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_CDN
ARG CONTAINERBASE_DEBUG
ARG CONTAINERBASE_LOG_LEVEL

RUN install-containerbase

#--------------------------------------
# Image: base
#--------------------------------------
FROM ${BASE_IMAGE} AS base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_CDN
ARG CONTAINERBASE_DEBUG
ARG CONTAINERBASE_LOG_LEVEL

#--------------------------------------
# Image: java
#--------------------------------------
FROM base AS test-java

# renovate: datasource=java-version packageName=java-jre
RUN install-tool java 21.0.4+7.0.LTS

#--------------------------------------
# Image: java
#--------------------------------------
FROM test-java AS test-gradle

# renovate: datasource=gradle-version packageName=gradle versioning=gradle
RUN install-tool gradle 8.10.1

#--------------------------------------
# Image: maven
#--------------------------------------
FROM test-java AS test-maven

# renovate: datasource=maven packageName=org.apache.maven:maven
RUN install-tool maven 3.9.9

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-java /.dummy /.dummy
COPY --from=test-gradle /.dummy /.dummy
COPY --from=test-maven /.dummy /.dummy
