#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:focal as base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

ARG TARGETARCH

COPY dist/docker/ /
COPY dist/cli/containerbase-cli-${TARGETARCH} /usr/local/containerbase/bin/containerbase-cli

RUN install-containerbase

#--------------------------------------
# Image: java
#--------------------------------------
FROM base as test-java

# renovate: datasource=java-version packageName=java-jre
RUN install-tool java 21.0.3+9.0.LTS

#--------------------------------------
# Image: java
#--------------------------------------
FROM test-java as test-gradle

# renovate: datasource=gradle-version packageName=gradle versioning=gradle
RUN install-tool gradle 8.7

#--------------------------------------
# Image: maven
#--------------------------------------
FROM test-java as test-maven

# renovate: datasource=maven packageName=org.apache.maven:maven
RUN install-tool maven 3.9.7

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-java /.dummy /.dummy
COPY --from=test-gradle /.dummy /.dummy
COPY --from=test-maven /.dummy /.dummy
