#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:focal as base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

COPY src/ /

RUN install-containerbase

#--------------------------------------
# Image: java
#--------------------------------------
FROM base as test-java

# renovate: datasource=adoptium-java packageName=java-jre
RUN install-tool java 17.0.7+7

#--------------------------------------
# Image: java
#--------------------------------------
FROM test-java as test-gradle

# renovate: datasource=gradle-version packageName=gradle versioning=gradle
RUN install-tool gradle 8.2.1

#--------------------------------------
# Image: maven
#--------------------------------------
FROM test-java as test-maven

# renovate: datasource=maven packageName=org.apache.maven:maven
RUN install-tool maven 3.9.3

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-java /.dummy /.dummy
COPY --from=test-gradle /.dummy /.dummy
COPY --from=test-maven /.dummy /.dummy
