ARG BASE_IMAGE=containerbase

#--------------------------------------
# Image: containerbase
#--------------------------------------
FROM ghcr.io/containerbase/ubuntu:24.04 AS containerbase

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

ARG TARGETARCH
COPY dist/docker/ /
COPY dist/cli/containerbase-cli-${TARGETARCH} /usr/local/containerbase/bin/containerbase-cli

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_CDN
ARG CONTAINERBASE_DEBUG
ARG CONTAINERBASE_LOG_LEVEL

RUN install-containerbase

#--------------------------------------
# Image: base
#--------------------------------------
FROM ${BASE_IMAGE} AS base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_CDN
ARG CONTAINERBASE_DEBUG
ARG CONTAINERBASE_LOG_LEVEL

#--------------------------------------
# Image: bazelisk
#--------------------------------------
FROM base AS test-bazelisk

# renovate: datasource=github-releases packageName=bazelbuild/bazelisk
RUN install-tool bazelisk v1.28.1

#--------------------------------------
# Image: bun
#--------------------------------------
FROM base AS test-bun

# renovate: datasource=npm
RUN install-tool bun 1.3.9

#--------------------------------------
# Image: deno
#--------------------------------------
FROM base AS test-deno

# renovate: datasource=github-releases packageName=denoland/deno
RUN install-tool deno 2.6.9

#--------------------------------------
# Image: apko
#--------------------------------------
FROM base AS test-apko

# renovate: datasource=github-releases packageName=chainguard-dev/apko
RUN install-tool apko 1.1.7

#--------------------------------------
# Image: devbox
#--------------------------------------
FROM base AS test-devbox

# renovate: datasource=github-releases packageName=jetify-com/devbox
RUN install-tool devbox 0.16.0

#--------------------------------------
# Image: gleam
#--------------------------------------
FROM base AS test-gleam

# renovate: datasource=github-releases packageName=gleam-lang/gleam
RUN install-tool gleam 1.14.0

#--------------------------------------
# Image: docker
#--------------------------------------
FROM base AS test-docker

# renovate: datasource=github-releases packageName=moby/moby
RUN install-tool docker v28.5.2

# renovate: datasource=github-releases packageName=docker/buildx
RUN install-tool buildx v0.31.1

# renovate: datasource=github-releases packageName=docker/compose
RUN install-tool docker-compose v5.0.2

RUN set -ex; \
  docker buildx version | grep github.com/docker/buildx; \
  docker compose version | grep 'Docker Compose version'; \
  true;

#--------------------------------------
# Image: git
#--------------------------------------
FROM base AS test-git

# renovate: datasource=github-tags packageName=git/git
RUN install-tool git v2.53.0

#--------------------------------------
# Image: git-lfs
#--------------------------------------
FROM test-git AS test-git-lfs

# renovate: datasource=github-releases packageName=git-lfs/git-lfs
RUN install-tool git-lfs v3.7.1

#--------------------------------------
# Image: helmfile
#--------------------------------------
FROM base AS test-helmfile

# renovate: datasource=github-releases packageName=helmfile/helmfile
RUN install-tool helmfile v1.2.3

#--------------------------------------
# Image: kustomize
#--------------------------------------
FROM base AS test-kustomize

# renovate: datasource=github-releases packageName=kubernetes-sigs/kustomize
RUN install-tool kustomize 5.8.1

#--------------------------------------
# Image: terraform
#--------------------------------------
FROM base AS test-terraform

# renovate: datasource=docker packageName=hashicorp/terraform versioning=docker
RUN install-tool terraform 1.14.5

#--------------------------------------
# Image: tofu
#--------------------------------------
FROM base AS test-tofu

# renovate: datasource=github-releases packageName=opentofu/opentofu
RUN install-tool tofu 1.11.5

#--------------------------------------
# Image: vendir
#--------------------------------------
FROM base AS test-vendir

# renovate: datasource=github-releases packageName=vmware-tanzu/carvel-vendir
RUN install-tool vendir v0.45.1

#--------------------------------------
# Image: others
#--------------------------------------
FROM base AS test-others

# renovate: datasource=github-releases packageName=kubernetes/kubernetes
RUN install-tool kubectl v1.35.1

# renovate: datasource=github-releases packageName=containerbase/skopeo-prebuild
RUN install-tool skopeo 1.22.0

# renovate: datasource=github-releases packageName=getsops/sops
RUN install-tool sops v3.11.0

# renovate: datasource=github-releases packageName=containerbase/wally-prebuild
RUN install-tool wally 0.3.2

# renovate: datasource=github-releases packageName=protocolbuffers/protobuf versioning=docker
RUN install-tool protoc 33.5

# renovate: datasource=github-releases packageName=prefix-dev/pixi
RUN install-tool pixi v0.63.2

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-bazelisk /.dummy /.dummy
COPY --from=test-bun /.dummy /.dummy
COPY --from=test-deno /.dummy /.dummy
COPY --from=test-apko /.dummy /.dummy
COPY --from=test-devbox /.dummy /.dummy
COPY --from=test-docker /.dummy /.dummy
COPY --from=test-git /.dummy /.dummy
COPY --from=test-git-lfs /.dummy /.dummy
COPY --from=test-gleam /.dummy /.dummy
COPY --from=test-helmfile /.dummy /.dummy
COPY --from=test-kustomize /.dummy /.dummy
COPY --from=test-terraform /.dummy /.dummy
COPY --from=test-tofu /.dummy /.dummy
COPY --from=test-vendir /.dummy /.dummy

COPY --from=test-others /.dummy /.dummy
