#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:focal as base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

COPY src/ /

RUN install-containerbase

#--------------------------------------
# Image: docker
#--------------------------------------
FROM base as test-docker

# renovate: datasource=github-releases packageName=moby/moby
RUN install-tool docker v24.0.6

#--------------------------------------
# Image: git
#--------------------------------------
FROM base as test-git

# renovate: datasource=github-tags packageName=git/git
RUN install-tool git v2.42.0

#--------------------------------------
# Image: git-lfs
#--------------------------------------
FROM test-git as test-git-lfs

# renovate: datasource=github-releases packageName=git-lfs/git-lfs
RUN install-tool git-lfs v3.4.0

#--------------------------------------
# Image: helmfile
#--------------------------------------
FROM base as test-helmfile

# renovate: datasource=github-releases packageName=helmfile/helmfile
RUN install-tool helmfile v0.156.0

#--------------------------------------
# Image: kustomize
#--------------------------------------
FROM base as test-kustomize

# renovate: datasource=github-releases packageName=kubernetes-sigs/kustomize
RUN install-tool kustomize 5.1.1

#--------------------------------------
# Image: terraform
#--------------------------------------
FROM base as test-terraform

# renovate: datasource=docker packageName=hashicorp/terraform versioning=docker
RUN install-tool terraform 1.5.6

#--------------------------------------
# Image: vendir
#--------------------------------------
FROM base as test-vendir

# renovate: datasource=github-releases packageName=vmware-tanzu/carvel-vendir
RUN install-tool vendir v0.34.4

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-docker /.dummy /.dummy
COPY --from=test-git /.dummy /.dummy
COPY --from=test-git-lfs /.dummy /.dummy
COPY --from=test-helmfile /.dummy /.dummy
COPY --from=test-kustomize /.dummy /.dummy
COPY --from=test-terraform /.dummy /.dummy
COPY --from=test-vendir /.dummy /.dummy
