ARG BASE_IMAGE=containerbase

#--------------------------------------
# Image: containerbase
#--------------------------------------
FROM ghcr.io/containerbase/ubuntu:20.04 AS containerbase

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

ARG TARGETARCH
COPY dist/docker/ /
COPY dist/cli/containerbase-cli-${TARGETARCH} /usr/local/containerbase/bin/containerbase-cli

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_CDN
ARG CONTAINERBASE_DEBUG
ARG CONTAINERBASE_LOG_LEVEL

RUN install-containerbase

#--------------------------------------
# Image: base
#--------------------------------------
FROM ${BASE_IMAGE} AS base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_CDN
ARG CONTAINERBASE_DEBUG
ARG CONTAINERBASE_LOG_LEVEL

#--------------------------------------
# Image: bazelisk
#--------------------------------------
FROM base AS test-bazelisk

# renovate: datasource=github-releases packageName=bazelbuild/bazelisk
RUN install-tool bazelisk v1.20.0

#--------------------------------------
# Image: bun
#--------------------------------------
FROM base AS test-bun

# renovate: datasource=npm
RUN install-tool bun 1.1.22

#--------------------------------------
# Image: gleam
#--------------------------------------
FROM base AS test-gleam

# renovate: datasource=github-releases packageName=gleam-lang/gleam
RUN install-tool gleam 1.4.1

#--------------------------------------
# Image: docker
#--------------------------------------
FROM base AS test-docker

# renovate: datasource=github-releases packageName=moby/moby
RUN install-tool docker v27.1.2

#--------------------------------------
# Image: git
#--------------------------------------
FROM base AS test-git

# renovate: datasource=github-tags packageName=git/git
RUN install-tool git v2.46.0

#--------------------------------------
# Image: git-lfs
#--------------------------------------
FROM test-git AS test-git-lfs

# renovate: datasource=github-releases packageName=git-lfs/git-lfs
RUN install-tool git-lfs v3.5.1

#--------------------------------------
# Image: helmfile
#--------------------------------------
FROM base AS test-helmfile

# renovate: datasource=github-releases packageName=helmfile/helmfile
RUN install-tool helmfile v0.167.1

#--------------------------------------
# Image: kustomize
#--------------------------------------
FROM base AS test-kustomize

# renovate: datasource=github-releases packageName=kubernetes-sigs/kustomize
RUN install-tool kustomize 5.4.3

#--------------------------------------
# Image: terraform
#--------------------------------------
FROM base AS test-terraform

# renovate: datasource=docker packageName=hashicorp/terraform versioning=docker
RUN install-tool terraform 1.9.4

#--------------------------------------
# Image: vendir
#--------------------------------------
FROM base AS test-vendir

# renovate: datasource=github-releases packageName=vmware-tanzu/carvel-vendir
RUN install-tool vendir v0.41.0

#--------------------------------------
# Image: others
#--------------------------------------
FROM base AS test-others

# renovate: datasource=github-releases packageName=kubernetes/kubernetes
RUN install-tool kubectl v1.30.3

# renovate: datasource=github-releases packageName=containerbase/skopeo-prebuild
RUN install-tool skopeo 1.16.0

# renovate: datasource=github-releases packageName=getsops/sops
RUN install-tool sops v3.9.0

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-bazelisk /.dummy /.dummy
COPY --from=test-bun /.dummy /.dummy
COPY --from=test-docker /.dummy /.dummy
COPY --from=test-git /.dummy /.dummy
COPY --from=test-git-lfs /.dummy /.dummy
COPY --from=test-gleam /.dummy /.dummy
COPY --from=test-helmfile /.dummy /.dummy
COPY --from=test-kustomize /.dummy /.dummy
COPY --from=test-terraform /.dummy /.dummy
COPY --from=test-vendir /.dummy /.dummy

COPY --from=test-others /.dummy /.dummy
