#--------------------------------------
# Image: base
#--------------------------------------
ARG BASE_IMAGE=containerbase/base

FROM ${BASE_IMAGE} as base

RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG
ARG GITHUB_TOKEN

RUN uname -p | tee | grep aarch64

#--------------------------------------
# Image: flux
#--------------------------------------
FROM base as test-flux

# renovate: datasource=github-releases packageName=fluxcd/flux2
RUN install-tool flux v2.2.2

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-flux /.dummy /.dummy
