#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:focal as base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

ARG TARGETARCH

COPY dist/docker/ /
COPY dist/cli/containerbase-cli-${TARGETARCH} /usr/local/containerbase/bin/containerbase-cli

RUN install-containerbase

#--------------------------------------
# Image: flux
#--------------------------------------
FROM base as test-flux

# renovate: datasource=github-releases packageName=fluxcd/flux2
RUN install-tool flux v2.2.2

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-flux /.dummy /.dummy
