#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:focal as base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

COPY src/ /

RUN install-containerbase

#--------------------------------------
# Image: flux
#--------------------------------------
FROM base as test-flux

# renovate: datasource=github-releases packageName=fluxcd/flux2
RUN install-tool flux v2.1.0

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-flux /.dummy /.dummy
