#--------------------------------------
# Image: base
#--------------------------------------
FROM ghcr.io/containerbase/ubuntu:20.04 AS base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_CDN
ARG CONTAINERBASE_DEBUG

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

ARG TARGETARCH

COPY dist/docker/ /
COPY dist/cli/containerbase-cli-${TARGETARCH} /usr/local/containerbase/bin/containerbase-cli

RUN install-containerbase

#--------------------------------------
# Image: python
#--------------------------------------
FROM base AS test-python

# renovate: datasource=github-releases packageName=containerbase/python-prebuild
RUN install-tool python 3.12.4

#--------------------------------------
# Image: checkov
#--------------------------------------
FROM test-python AS test-checkov

# renovate: datasource=pypi
RUN install-tool checkov 3.2.209

#--------------------------------------
# Image: hashin
#--------------------------------------
FROM test-python AS test-hashin

# renovate: datasource=pypi
RUN install-tool hashin 1.0.1

#--------------------------------------
# Image: pipenv
#--------------------------------------
FROM test-python AS test-pipenv

# renovate: datasource=pypi
RUN install-tool pipenv 2024.0.1

#--------------------------------------
# Image: poetry
#--------------------------------------
FROM test-python AS test-poetry

# renovate: datasource=pypi
RUN install-tool poetry 1.8.3

#--------------------------------------
# Image: conan
#--------------------------------------
FROM test-python AS test-conan

# renovate: datasource=pypi
RUN install-tool conan 2.5.0

#--------------------------------------
# Image: copier
#--------------------------------------
FROM test-python as test-copier

# renovate: datasource=pypi
RUN install-tool copier 9.3.1

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-checkov /.dummy /.dummy
COPY --from=test-conan /.dummy /.dummy
COPY --from=test-copier /.dummy /.dummy
COPY --from=test-hashin /.dummy /.dummy
COPY --from=test-pipenv /.dummy /.dummy
COPY --from=test-poetry /.dummy /.dummy
