ARG BASE_IMAGE=containerbase

#--------------------------------------
# Image: containerbase
#--------------------------------------
FROM ghcr.io/containerbase/ubuntu:20.04 AS containerbase

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

ARG TARGETARCH
COPY dist/docker/ /
COPY dist/cli/containerbase-cli-${TARGETARCH} /usr/local/containerbase/bin/containerbase-cli

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_CDN
ARG CONTAINERBASE_DEBUG
ARG CONTAINERBASE_LOG_LEVEL

RUN install-containerbase

#--------------------------------------
# Image: base
#--------------------------------------
FROM ${BASE_IMAGE} AS base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_CDN
ARG CONTAINERBASE_DEBUG
ARG CONTAINERBASE_LOG_LEVEL

#--------------------------------------
# Image: python
#--------------------------------------
FROM base AS test-python

# renovate: datasource=github-releases packageName=containerbase/python-prebuild
RUN install-tool python 3.12.5

#--------------------------------------
# Image: checkov
#--------------------------------------
FROM test-python AS test-checkov

# renovate: datasource=pypi
RUN install-tool checkov 3.2.217

#--------------------------------------
# Image: hashin
#--------------------------------------
FROM test-python AS test-hashin

# renovate: datasource=pypi
RUN install-tool hashin 1.0.1

#--------------------------------------
# Image: pipenv
#--------------------------------------
FROM test-python AS test-pipenv

# renovate: datasource=pypi
RUN install-tool pipenv 2024.0.1

#--------------------------------------
# Image: poetry
#--------------------------------------
FROM test-python AS test-poetry

# renovate: datasource=pypi
RUN install-tool poetry 1.8.3

#--------------------------------------
# Image: conan
#--------------------------------------
FROM test-python AS test-conan

# renovate: datasource=pypi
RUN install-tool conan 2.6.0

#--------------------------------------
# Image: copier
#--------------------------------------
FROM test-python AS test-copier

# renovate: datasource=pypi
RUN install-tool copier 9.3.1


#--------------------------------------
# Image: uv
#--------------------------------------
FROM test-python AS test-uv

# renovate: datasource=pypi
RUN install-tool uv 0.2.37

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-checkov /.dummy /.dummy
COPY --from=test-conan /.dummy /.dummy
COPY --from=test-copier /.dummy /.dummy
COPY --from=test-hashin /.dummy /.dummy
COPY --from=test-pipenv /.dummy /.dummy
COPY --from=test-poetry /.dummy /.dummy
COPY --from=test-uv /.dummy /.dummy
