#--------------------------------------
# Image: base
#--------------------------------------
ARG BASE_IMAGE=containerbase/base

FROM ${BASE_IMAGE} as base

RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG
ARG GITHUB_TOKEN

RUN uname -p | tee | grep aarch64

#--------------------------------------
# Image: helm
#--------------------------------------
FROM base as test-helm

# renovate: datasource=github-releases packageName=helm/helm
RUN install-tool helm v3.14.0

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-helm /.dummy /.dummy
