#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:focal as base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_CDN
ARG CONTAINERBASE_DEBUG

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

ARG TARGETARCH

COPY dist/docker/ /
COPY dist/cli/containerbase-cli-${TARGETARCH} /usr/local/containerbase/bin/containerbase-cli

RUN install-containerbase

#--------------------------------------
# Image: helm
#--------------------------------------
FROM base as test-helm

# renovate: datasource=github-releases packageName=helm/helm
RUN install-tool helm v3.15.1

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-helm /.dummy /.dummy
