#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:focal as base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

COPY src/ /

RUN install-containerbase

#--------------------------------------
# Image: nix
#--------------------------------------
FROM base as test-nix

# renovate: datasource=github-tags packageName=NixOS/nix
RUN install-tool nix 2.14.1

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-nix /.dummy /.dummy
