#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:focal as base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

COPY src/ /

RUN install-buildpack

#--------------------------------------
# Image: test
#--------------------------------------
FROM base as test-dart

# renovate datasource=docker
RUN install-tool dart 2.18.0

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-dart /.dummy /.dummy
