#--------------------------------------
# Image: base
#--------------------------------------
ARG BASE_IMAGE=containerbase/base

FROM ${BASE_IMAGE} as base

RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG
ARG GITHUB_TOKEN

RUN uname -p | tee | grep aarch64


#--------------------------------------
# Image: test
#--------------------------------------
FROM base as test-dart

# renovate: datasource=docker
RUN install-tool dart 2.19.6

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-dart /.dummy /.dummy
