#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:focal as base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

ARG TARGETARCH

COPY dist/docker/ /
COPY dist/cli/containerbase-cli-${TARGETARCH} /usr/local/containerbase/bin/containerbase-cli

RUN install-containerbase

#--------------------------------------
# Image: rye
#--------------------------------------
FROM base as test-rye

# renovate: datasource=github-releases packageName=astral-sh/rye
RUN install-tool rye 0.34.0

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-rye /.dummy /.dummy
