#--------------------------------------
# Image: base
#--------------------------------------
ARG BASE_IMAGE=containerbase/base

FROM ${BASE_IMAGE} as base

RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG
ARG GITHUB_TOKEN

RUN uname -p | tee | grep aarch64

#--------------------------------------
# Image: dotnet
#--------------------------------------
FROM base as test-dotnet

# renovate: datasource=dotnet packageName=dotnet-sdk
RUN install-tool dotnet 8.0.101

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-dotnet /.dummy /.dummy
