import { mkdir, mkdtemp, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';
import { z } from 'zod';
import type { SupportedTools } from '../packages/base/src/schema.ts';
import { SupportedTools as SupportedToolsSchema } from '../packages/base/src/schema.ts';

// generates the data of the `@containerbase/base` package
const pkgDir = new URL('../packages/base/', import.meta.url);

// the install services read from and write below `<rootDir>`, so run them
// against a temporary root which only links the shell tools of this repo
const rootDir = await mkdtemp(join(tmpdir(), 'containerbase-tools-'));
await mkdir(join(rootDir, 'usr/local'), { recursive: true });
await symlink(
  fileURLToPath(new URL('../src/usr/local/containerbase', import.meta.url)),
  join(rootDir, 'usr/local/containerbase'),
  'dir',
);
globalThis.rootDir = rootDir;

const { listSupportedTools } = await import('../src/cli/install-tool/index.ts');

async function write(file: string, content: string): Promise<void> {
  const target = fileURLToPath(new URL(file, pkgDir));
  const options = await resolveConfig(target);
  await writeFile(
    target,
    await format(content, { ...options, filepath: target }),
    { encoding: 'utf8' },
  );
}

const tools: SupportedTools['tools'] = {};

try {
  for (const { name, ...metadata } of await listSupportedTools()) {
    tools[name] = metadata;
  }
} finally {
  await rm(rootDir, { recursive: true, force: true });
}

await mkdir(new URL('data/', pkgDir), { recursive: true });

await write('data/tools.json', JSON.stringify({ tools }));

await write(
  'data/tools.schema.json',
  JSON.stringify(z.toJSONSchema(SupportedToolsSchema)),
);

await write(
  'src/data.ts',
  `// generated by \`pnpm tools\`, do not edit
import type { ToolMetadata } from './types.ts';

/**
 * All tools \`install-tool\` supports, sorted by name.
 */
export const tools = ${JSON.stringify(tools)} as const satisfies Record<
  string,
  ToolMetadata
>;
`,
);
