#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:focal as base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

COPY src/ /

RUN install-containerbase

# currently go doesn't install git
# renovate: datasource=github-tags packageName=git/git
RUN install-tool git v2.41.0

#--------------------------------------
# Image: golang
#--------------------------------------
FROM base as test-golang

# renovate: datasource=docker versioning=docker
RUN install-tool golang 1.20.5

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-golang /.dummy /.dummy
