#--------------------------------------
# Image: base
#--------------------------------------
ARG BASE_IMAGE=containerbase/base

FROM ${BASE_IMAGE} as base

RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG
ARG GITHUB_TOKEN

RUN uname -p | tee | grep aarch64

#--------------------------------------
# Image: golang
#--------------------------------------
FROM base as test-golang

# renovate: datasource=docker versioning=docker
RUN install-tool golang 1.21.6

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-golang /.dummy /.dummy
