#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:focal as base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG

COPY src/ /

RUN install-buildpack

#--------------------------------------
# Image: php
#--------------------------------------
FROM base as test-php

# renovate: datasource=github-releases packageName=containerbase/php-prebuild
RUN install-tool php 8.2.4
#--------------------------------------
# Image: composer
#--------------------------------------
FROM test-php as test-composer

# renovate: datasource=github-releases packageName=composer/composer
RUN install-tool composer 2.5.5

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-php /.dummy /.dummy
COPY --from=test-composer /.dummy /.dummy
