#--------------------------------------
# Image: base
#--------------------------------------
FROM ubuntu:focal as base

RUN uname -p | tee | grep aarch64
RUN touch /.dummy

ARG APT_HTTP_PROXY
ARG CONTAINERBASE_DEBUG

ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

ARG TARGETARCH

COPY dist/docker/ /
COPY dist/cli/containerbase-cli-${TARGETARCH} /usr/local/containerbase/bin/containerbase-cli

RUN install-containerbase

#--------------------------------------
# Image: php
#--------------------------------------
FROM base as test-php

# renovate: datasource=github-releases packageName=containerbase/php-prebuild
RUN install-tool php 8.3.7
#--------------------------------------
# Image: composer
#--------------------------------------
FROM test-php as test-composer

# renovate: datasource=github-releases packageName=composer/composer
RUN install-tool composer 2.7.6

#--------------------------------------
# Image: final
#--------------------------------------
FROM base

COPY --from=test-php /.dummy /.dummy
COPY --from=test-composer /.dummy /.dummy
