name: build-push

on:
  push:
    branches-ignore:
      - gh-readonly-queue/**
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && github.ref_name || github.run_number }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  DRY_RUN: ${{ github.ref_name != github.event.repository.default_branch && !startsWith(github.ref_name, 'maint/') }}
  OWNER: ${{ github.repository_owner }}
  FILE: base
  BUILDKIT_PROGRESS: plain
  BUILDX_NO_DEFAULT_LOAD: 1
  CONTAINERBASE_VERSION: ${{ github.sha }}
  APT_HTTP_PROXY: http://172.17.0.1:8000

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      checks: write
      id-token: write

  release:
    needs: [build]
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    concurrency:
      group: ${{ github.workflow }}-release-${{ github.ref_name }}
      # never cancel a release that has already started, as it may have started pushing artifacts
      cancel-in-progress: ${{ github.event_name != 'push' }}

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: docker-config
        uses: containerbase/internal-tools@b2bcaa57bb0394ae57cd84d0dc2de9bf136a17bb # v4.6.49
        with:
          command: docker-config

      # full checkout for semantic-release
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          show-progress: false
          filter: blob:none # we don't need all blobs

      - name: Check system
        uses: ./.github/actions/check

      # allow build cross arch images
      - uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: init
        run: |
          echo "OWNER=${OWNER,,}" >> ${GITHUB_ENV}
          echo "CACHE_WEEK=$(date +%U)" >> $GITHUB_ENV

      - name: ⚙️ Setup
        uses: containerbase/internal-tools/setup@b2bcaa57bb0394ae57cd84d0dc2de9bf136a17bb # v4.6.49
        with:
          checkout: false
          apt-proxy: true

      - name: Docker registry login
        if: github.ref_name == github.event.repository.default_branch || startsWith(github.ref_name, 'maint/')
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: semantic-release
        if: github.event_name == 'push'
        run: pnpm semantic-release --dry-run ${{env.DRY_RUN}} --ci ${{env.DRY_RUN != 'true'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: semantic-release:github
