name: build

on:
  workflow_call:

env:
  OWNER: ${{ github.repository_owner }}
  FILE: base
  BUILDKIT_PROGRESS: plain
  BUILDX_NO_DEFAULT_LOAD: 1
  CONTAINERBASE_VERSION: ${{ github.sha }}
  APT_HTTP_PROXY: http://172.17.0.1:8000
  HUSKY: 0

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    outputs:
      uid: ${{ steps.init.outputs.uid }}

    steps:
      - name: ⚙️ Setup
        uses: containerbase/internal-tools/setup@1dd7882986cbda6e6ac247b70a67305bc68745bb # v4.6.37
        with:
          save-cache: true

      - name: ⚙️ Init
        id: init
        run: echo "uid=$(uuidgen)" >> ${GITHUB_OUTPUT}

  lint:
    runs-on: ubuntu-24.04
    needs: setup
    timeout-minutes: 15
    permissions:
      contents: read
      checks: write

    steps:
      - name: ⚙️ Setup
        uses: containerbase/internal-tools/setup@1dd7882986cbda6e6ac247b70a67305bc68745bb # v4.6.37

      - name: lint
        run: |
          pnpm eslint -f gha
          pnpm prettier
          pnpm lint:markdown
          pnpm lint:types

      - name: shellcheck
        if: ${{ github.event_name != 'merge_group' }}
        uses: reviewdog/action-shellcheck@4c07458293ac342d477251099501a718ae5ef86e # v1.32.0
        with:
          fail_level: any
          reporter: github-pr-annotations
          filter_mode: nofilter
          path: |
            src
            .husky
          pattern: |
            *.sh
            *.bats
          check_all_files_with_shebangs: 'true'

  bats:
    runs-on: ubuntu-24.04
    needs: setup
    timeout-minutes: 15

    steps:
      - name: ⚙️ Setup
        uses: containerbase/internal-tools/setup@1dd7882986cbda6e6ac247b70a67305bc68745bb # v4.6.37

      - name: Install ubuntu dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install -y libarchive-tools

      - name: build
        run: pnpm build

      - name: bats
        run: pnpm test:bats

  vitest:
    runs-on: ubuntu-24.04
    needs: setup
    timeout-minutes: 15
    permissions:
      id-token: write

    steps:
      - name: ⚙️ Setup
        uses: containerbase/internal-tools/setup@1dd7882986cbda6e6ac247b70a67305bc68745bb # v4.6.37

      - name: vitest
        run: pnpm test:vitest

      - name: Codecov test results
        if: github.event_name != 'merge_group' && !cancelled()
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          use_oidc: true
          report_type: test_results

      - name: Codecov coverage results
        if: github.event_name != 'merge_group'
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          use_oidc: true

  build:
    runs-on: ubuntu-24.04
    needs: setup
    timeout-minutes: 15

    steps:
      - name: ⚙️ Setup
        uses: containerbase/internal-tools/setup@1dd7882986cbda6e6ac247b70a67305bc68745bb # v4.6.37

      - name: build
        run: pnpm build

      - name: upload dist
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dist
          path: |
            dist/

  base:
    runs-on: ${{ matrix.arch.os }}
    name: base (${{ matrix.arch.name }})
    needs:
      - setup
      - build

    strategy:
      fail-fast: false
      matrix:
        arch:
          - name: x86_64
            os: ubuntu-24.04
            tag: amd64
          - name: aarch64
            os: ubuntu-24.04-arm
            tag: arm64

    steps:
      - name: ⚙️ Setup
        uses: containerbase/internal-tools/setup@1dd7882986cbda6e6ac247b70a67305bc68745bb # v4.6.37
        with:
          node: false
          apt-proxy: true

      - name: Check system
        uses: ./.github/actions/check

      - name: ⚙️ Init
        run: |
          echo "OWNER=${OWNER,,}" >> ${GITHUB_ENV}
          echo "BASE=ttl.sh/${{ needs.setup.outputs.uid }}/${{ matrix.arch.tag }}:1d" >> ${GITHUB_ENV}

      - name: build base
        uses: ./.github/actions/bake
        with:
          args: >-
            --set build-ttl.tags=${{env.BASE}}
            --set build-ttl.cache-to=type=gha,mode=max,scope=${{ needs.setup.outputs.uid }}-${{ matrix.arch.tag }}
            --set settings.cache-from+=type=gha,scope=${{ needs.setup.outputs.uid }}-${{ matrix.arch.tag }}
            build-ttl

  distro:
    runs-on: ubuntu-24.04
    needs:
      - bats
      - lint
      - vitest
      - build

    strategy:
      fail-fast: false
      matrix:
        distro:
          - jammy
          - noble
          - resolute

    env:
      TAG: ${{ matrix.distro }}

    steps:
      - name: ⚙️ Setup
        uses: containerbase/internal-tools/setup@1dd7882986cbda6e6ac247b70a67305bc68745bb # v4.6.37
        with:
          node: false
          apt-proxy: true

      - name: Check system
        uses: ./.github/actions/check

      - name: ⚙️  Init
        run: |
          echo "OWNER=${OWNER,,}" >> ${GITHUB_ENV}

      - name: test distro
        uses: ./.github/actions/bake
        with:
          args: test-distro

  # test old distros on arm64
  base-arm64:
    runs-on: ubuntu-24.04-arm
    needs:
      - bats
      - lint
      - vitest
      - build
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        distro:
          - jammy
          - resolute

    env:
      TAG: ${{ matrix.distro }}

    steps:
      - name: ⚙️ Setup
        uses: containerbase/internal-tools/setup@1dd7882986cbda6e6ac247b70a67305bc68745bb # v4.6.37
        with:
          node: false
          apt-proxy: true

      - name: Check system
        uses: ./.github/actions/check

      - name: ⚙️  Init
        run: |
          echo "OWNER=${OWNER,,}" >> ${GITHUB_ENV}

      - name: test distro
        uses: ./.github/actions/bake
        with:
          args: test-base

  lang:
    runs-on: ${{ matrix.arch.os }}
    name: ${{ matrix.lang }} (${{ matrix.arch.name }})
    needs:
      - setup
      - base
      - bats
      - lint
      - vitest

    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        lang:
          - dart
          - dotnet
          - erlang
          - flutter
          - flux
          - golang
          - haskell
          - java
          - jb
          - helm
          - nix
          - node
          - php
          - powershell
          - python
          - ruby
          - rust
          - swift
          - latest
        arch:
          - name: x86_64
            os: ubuntu-24.04
            tag: amd64
          - name: aarch64
            os: ubuntu-24.04-arm
            tag: arm64
        # include:
        #   # no ubuntu arm64 support for haskell
        #   - lang: haskell
        #     arch:
        #       name: x86_64
        #       os: ubuntu-24.04
        #       tag: amd64

    env:
      TAG: ${{ matrix.lang }}

    steps:
      - name: ⚙️ Setup
        uses: containerbase/internal-tools/setup@1dd7882986cbda6e6ac247b70a67305bc68745bb # v4.6.37
        with:
          node: false
          apt-proxy: true

      - name: Check system
        uses: ./.github/actions/check

      - name: ⚙️ Init
        run: |
          echo "OWNER=${OWNER,,}" >> ${GITHUB_ENV}
          echo "BASE_IMAGE=ttl.sh/${{ needs.setup.outputs.uid }}/${{ matrix.arch.tag }}:1d" >> ${GITHUB_ENV}

      - name: build base
        uses: ./.github/actions/bake
        with:
          args: >-
            --set build-ttl.tags=${{env.BASE_IMAGE}}
            --set build-ttl.cache-to=type=gha,mode=max,scope=${{ needs.setup.outputs.uid }}-${{ matrix.arch.tag }}
            --set settings.cache-from+=type=gha,scope=${{ needs.setup.outputs.uid }}-${{ matrix.arch.tag }}
            build-ttl

      - name: test distro
        uses: ./.github/actions/bake
        with:
          args: test-${{ matrix.arch.name }}

  # Catch-all required check for test matrix
  test-success:
    needs:
      - base-arm64
      - distro
      - lang
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    if: always()
    steps:
      - name: Fail for failed or cancelled distro tests
        if: |
          needs.base-arm64.result == 'failure' ||
          needs.base-arm64.result == 'cancelled'
        run: exit 1

      - name: Fail for failed or cancelled distro tests
        if: |
          needs.distro.result == 'failure' ||
          needs.distro.result == 'cancelled'
        run: exit 1

      - name: Fail for failed or cancelled lang tests
        if: |
          needs.lang.result == 'failure' ||
          needs.lang.result == 'cancelled'
        run: exit 1
