name: devcontainer
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read

jobs:
  devcontainer-test:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.draft != true
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build and run dev container task
        uses: devcontainers/ci@a04f23f34b07f51f61fb93fc35bae584f4b3b3f2 # v0.3.1900000405
        with:
          runCmd: pnpm build
